services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -h localhost"]
      interval: 2s
      timeout: 2s
      retries: 15
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      # збігається з ENV у Dockerfile; можна перевизначити тут
      DATABASE_URL: postgres://postgres:postgres@db:5433/postgres
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
