version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: acid_lab
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}